### PR TITLE
Fix the tests - add workflow

### PR DESCRIPTION
**Pull request by snogge**
Fixed the tests so they work on Emacs 25.1 up until current Emacs master.
Add github workflow to run the tests on pushes and pull requests.

### CODE REVIEW

**Comment by canatella** [comment]
Thanks, look good.

Before I merge this without any testing...
I haven't been using repo for a long time, would you care taking over this package ? It doesn't need much work and as I'm not using it myself, it's cumbersome to test for me. 
Feel free to refuse, but this package might benefit from having an actual user as a maintainer :)

**Comment by snogge** [comment]
Sure, I can take it over. 
I assume this means you will transfer the github project to me?  An organization would work, but feels like overkill at this point. 
I do not want to maintain the project under someone elses account, I'm doing that with emacs-buttercup and I'm beginning to feel the pain.
I've never been involved with the transfer of projects before, do you know if github handles redirects for things like melpa?

**Comment by canatella** [comment]
Looking at https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository, it does seem github will redirect everything, so Melpa should keep working, but I'll still create a PR on melpa to point to the new repo.

**Comment by snogge** [comment]
I have deleted my fork, I think that was required for the transfer to work. 
The transfer request has to be approved be me within 24 hours, please ping me here as well when you have started the transfer so I don't miss the email.

**Comment by canatella** [comment]
Started the transfer!

**Comment by snogge** [comment]
Transfer complete.  Thank you @canatella.

**Pull request closed without merging**
